<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyName>KubeShell.KubernetesClient</AssemblyName>
    <RootNamespace>KubeShell.Backends.KubernetesClient</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Runtime/KubeShell.Runtime/KubeShell.Runtime.csproj" />
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
  </ItemGroup>
</Project>
