@{
    RootModule        = 'KubeShell.psm1'
    ModuleVersion     = '0.3.0'
    GUID              = 'b01da0de-15ef-4e95-8b3d-43ca6866228e'
    Author            = 'KubeShell contributors'
    Description       = 'Object-oriented, modular PowerShell shell layer for Kubernetes with a small semantic Runtime and pluggable Kubernetes backends.'
    PowerShellVersion = '7.4'
    FormatsToProcess  = @('Formatting/KubeShell.Format.ps1xml')
    FunctionsToExport = @(
        'Get-KubeResource',
        'Get-KubePod',
        'Get-KubeDeployment',
        'Get-KubeStatefulSet',
        'Get-KubeDaemonSet',
        'Get-KubeReplicaSet',
        'Get-KubeJob',
        'Get-KubeCronJob',
        'Get-KubeService',
        'Get-KubeIngress',
        'Get-KubeConfigMap',
        'Get-KubeSecret',
        'Get-KubeSecretValue',
        'Get-KubeNode',
        'Get-KubeNamespace',
        'Get-KubePersistentVolumeClaim',
        'Get-KubePersistentVolume',
        'Get-KubeStorageClass',
        'Get-KubeEndpointSlice',
        'Get-KubeRole',
        'Get-KubeRoleBinding',
        'Get-KubeClusterRole',
        'Get-KubeClusterRoleBinding',
        'Get-KubeEvent',
        'Get-KubeContainer',
        'Get-KubeKind',
        'Get-KubeSchema',
        'Get-KubeSchemaField',
        'Watch-KubeResource',
        'Get-KubeLog',
        'Invoke-KubeExec',
        'Enter-KubePod',
        'Restart-KubeDeployment',
        'Set-KubeDeploymentScale',
        'Wait-KubeRollout',
        'Undo-KubeRollout',
        'Set-KubeImage',
        'Remove-KubeResource',
        'Remove-KubePod',
        'Suspend-KubeCronJob',
        'Resume-KubeCronJob',
        'Enter-KubeDebugPod',
        'Enter-KubeNode',
        'Start-KubePortForward',
        'Stop-KubePortForward',
        'Copy-ToKubePod',
        'Copy-FromKubePod',
        'Set-KubeManifest',
        'Test-KubeManifest',
        'Compare-KubeManifest',
        'Remove-KubeManifest',
        'Set-KubeResourcePatch',
        'Set-KubeObject',
        'Get-KubeYaml',
        'Get-KubeJson',
        'ConvertFrom-KubeYaml',
        'ConvertTo-KubeYaml',
        'Get-KubeCondition',
        'Get-KubeOwner',
        'Get-KubeDependent',
        'Get-KubeEventsFor',
        'Test-KubePod',
        'Test-KubeDeployment',
        'Test-KubeCluster',
        'Test-KubeAccess',
        'Get-KubeTopPod',
        'Get-KubeTopNode',
        'Get-KubeNodeAllocation',
        'Get-KubeOvercommit',
        'Resolve-KubeService',
        'Test-KubeService',
        'Test-KubeDns',
        'Get-KubeConfigurationStorePath',
        'Get-KubeConfigSet',
        'New-KubeConfigSet',
        'Set-KubeConfigSet',
        'Remove-KubeConfigSet',
        'Use-KubeConfigSet',
        'Get-KubeProfile',
        'New-KubeProfile',
        'Set-KubeProfile',
        'Remove-KubeProfile',
        'Use-KubeProfile',
        'Get-KubeSession',
        'Clear-KubeSession',
        'Invoke-KubeProfile',
        'Invoke-KubeConfigSet',
        'Set-KubeConfigEnvironment',
        'Get-KubeContext',
        'Set-KubeContext',
        'Get-KubeCurrentNamespace',
        'Set-KubeNamespace',
        'Push-KubeContext',
        'Pop-KubeContext',
        'Get-KubePromptSegment',
        'Enable-KubePrompt',
        'Disable-KubePrompt',
        'Set-KubeBookmark',
        'Get-KubeBookmark',
        'Remove-KubeBookmark',
        'Use-KubeBookmark',
        'Select-KubeResource',
        'Invoke-Kubectl',
        'Enable-KubeCompletion'
    )
    AliasesToExport   = @('kgp','kgd','kgs','kgn','kge','klog','kx','kwatch')
    CmdletsToExport   = @()
    VariablesToExport = @()
    PrivateData = @{
        PSData = @{
            Tags       = @('Kubernetes','kubectl','PowerShell','DevOps','KubeShell')
            Prerelease = 'alpha11'
        }
    }
}
