<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>KubeShell.Tests.ProviderBackend</AssemblyName>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Runtime/KubeShell.Runtime/KubeShell.Runtime.csproj" />
  </ItemGroup>
</Project>
